init dot_juice

diff --git a/build b/build
--- a/build
+++ b/build
@@ -3,54 +3,67 @@ cd /tmp/rom # Depends on where source got synced
 
 # Normal build steps
 . build/envsetup.sh
-lunch aosp_mido-user
+lunch dot_juice-user
 export CCACHE_DIR=/tmp/ccache
 export CCACHE_EXEC=$(which ccache)
 export USE_CCACHE=1
-ccache -M 20G # It took only 6.4GB for mido
+export WITH_GAPPS=true 
+export DOT_OFFICIAL=true
+ccache -M 20G # It took only 6.4GB for juice
 ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
 ccache -z # Clear old stats, so monitor script will provide real ccache statistics
+
+#tg
+tg(){
+	bot_api=$bot_api # Your tg bot api, dont use my one haha, it's better to encrypt bot api too.
+	your_telegram_id=$1 # No need to touch
+	msg=$2 # No need to touch
+	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}&parse_mode=html"
+}
+id=272503335 # Your telegram id
+tg $id "*juice ROM Compile Status*: \`STARTED!\`.
+*Started at*:- \`$(date)\`."
 
 # Next 8 lines should be run first to collect ccache and then upload, after doning it 1 or 2 times, our ccache will help to build without these 8 lines.
 #make api-stubs-docs || echo no problem, we need ccache
 #make system-api-stubs-docs || echo no problem we need ccache
 #make test-api-stubs-docs || echo no problem, we need ccache
-#make aex -j10 & # dont remove that '&'
-#sleep 85m
-#kill %1
-#ccache -s
+make bacon -j8 & # dont remove that '&'
+sleep 90m
+kill %1
+ccache -s
 #and dont use below codes for first 1 or 2 times, to get ccache uploaded,
 
 
 # upload function for uploading rom zip file! I don't want unwanted builds in my google drive haha!
-up(){
-	curl --upload-file $1 https://transfer.sh/$(basename $1); echo
-	# 14 days, 10 GB limit
-}
+#up(){
+#	curl --upload-file $1 https://transfer.sh/$(basename $1); echo
+#	# 14 days, 10 GB limit
+#}
 
 # It's recommended to use google drive(rclone) as upload solution for coping with the time limit. Un-comment next 3 lines to upload with rclone in drive. Also change apon and junk according to your config name, uploading folder of drive
 #up(){
-#	time rclone copy $1 apon:junk -P # apon is my rclone config name, 
+#	time rclone copy $1 juice:dotOS -P # juice is my rclone config name, 
 #}
 
-tg(){
-	bot_api=1692865707:AAHvKZogI5sUGtqjd2sZvNl8tib0Q_xcYkY # Your tg bot api, dont use my one haha, it's better to encrypt bot api too.
-	your_telegram_id=$1 # No need to touch 
-	msg=$2 # No need to touch
-	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}"
-}
 
-id=571213272 # Your telegram id
+mkdir -p ~/.config/rclone
+echo "$rclone_config" > ~/.config/rclone/rclone.conf
 
 # Upload rom zip file if succeed to build! Send notification to tg! And send shell to tg if build fails!
 
 # Let's compile by parts! Coz of ram issue!
-make api-stubs-docs || echo no problem
-make system-api-stubs-docs || echo no problem
-make test-api-stubs-docs || echo no problem
+#make api-stubs-docs || echo no problem
+#make system-api-stubs-docs || echo no problem
+#make test-api-stubs-docs || echo no problem
 
-make aex -j10 \
-	&& send_zip=$(up out/target/product/mido/*zip) && tg $id "Build Succeed!
-$send_zip" \
-	|| tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') && tg $id "Build Failed" && tg $id "$send_shell" && ccache -s && sleep 2h
-ccache -s # Let's print ccache statistics finally
+#make bacon -j8 \
+#	&& send_zip=$(up out/target/product/juice/*zip) && tg $id "Build Succeed! $send_zip"
+#tg $id "*juice Compile Status*: \`FINISHED!\`
+#*Finished at*:- \`$(date)\`.
+#*Compile Time*: \`$((build_time / 3600)) hour(s), $((build_time % 3600 / 60)) minute(s) and $((build_time % 60)) seconds\`.
+#*Download Link*: [juice](https://rom.aseelpsathar-romdev.workers.dev/dotOS/)
+#*CCache Stats*:-
+#\`$(ccache -s | sed -n -e "6,9 p" -e "9 q")\` $send_zip"
+#	|| tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') && tg $id #"*juice ROM Compile Status*:\'Build Failed'" && tg $id "$send_shell" && ccache -s && sleep 2h
+#ccache -s # Let's print ccache statistics finally
